# Generated by Django 4.2.2 on 2023-07-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlist',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='location',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='event_access',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='start_date',
        ),
    ]
