# Generated by Django 4.2.2 on 2023-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_end_date_eventlist_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerdetail',
            name='event_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speakerdetail',
            name='event_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speakerdetail',
            name='event_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speakerdetail',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
